### ISSUE TITLE
Things to check

### ISSUE THREAD

**Issue by italo-batista** [ufcg-lsd/iguassu#3]
-  Iguassu makes use of Fogbow to request workers for executing tasks (commands). Currently, the blowout lib (dependency in Iguassu) makes use of fogbow-mono-manager API. However, blowout will use the new API for Fogbow, the RAS (Resource Allocation Service). I think this will change the way Iguassu will communicate with workers, because the RAS will not implement the Reverse-Tunnel abstraction. The new API (RAS) implies that every worker will have its own public ip, and ssh will be in default port.

- Check if this following situation happens: If a task is submitted and there is one worker available to run this task, but this worker dies before task starts, this task will never be executed, even if new workers become available.

**Comment by emanueljoivo** [comment]
Outdated in our current context (e.g. blowout is not a dependency anymore).
